#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# install dependencies

echo "Checking for yt-dlp..."
if ! command -v yt-dlp %> /dev/null
then
    if ! command -v brew &> /dev/null
    then
      echo "yt-dlp could not be found and homebrew is not installed. Please install yt-dlp manually or install homebrew."
      exit 1
    else
      echo "Installing yt-dlp via homebrew..."
      brew install yt-dlp
    fi
else
  echo "yt-dlp already installed, skipping."
fi

echo "Checking for ffmpeg..."
if ! command -v ffmpeg %> /dev/null
then
    if ! command -v brew &> /dev/null
    then
      echo "ffmpeg could not be found and homebrew is not installed. Please install ffmpeg manually or install homebrew."
      exit 1
    else
      echo "Installing ffmpeg via homebrew..."
      brew install ffmpeg
    fi
else
  echo "ffmpeg already installed, skipping."
fi

echo "Done."
